apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: project-leaders
users:
  - developer
  - cprakash
  - user1
  - user2 
  - user3
  - user4
  - user5
  - user6 
  - user7
  - user8
  - user9


